import{a as q,i as c,S as P}from"./assets/vendor-u8rapaCG.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const $="46313967-d4d30fae59777882921d7e8bb";async function v(r,s){const n=`https://pixabay.com/api/?${new URLSearchParams({key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s})}`;try{return(await q.get(n)).data}catch(e){throw console.error("Error fetching images:",e),e}}const E=document.querySelector(".gallery");function M(r){const s=r.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:i,comments:w,downloads:S})=>`
<li class="gallery-item">
                <a href="${n}" class="gallery-link">
                    <img src="${o}" alt="${e}" class="gallery-image" /></a>
                  <div class="info">
                    <p class="info-item"><span>Likes:</span> ${t}</p>
                    <p class="info-item"><span>Views:</span> ${i}</p>
                    <p class="info-item"><span>Comments:</span> ${w}</p>
                    <p class="info-item"><span>Downloads:</span> ${S}</p>
                </div>
            </li>`).join("");E.insertAdjacentHTML("beforeend",s)}const p=document.querySelector(".loader"),a=document.querySelector(".load-more"),g=document.querySelector(".search-form"),y=document.querySelector(".gallery");function h(){p.style.display="flex"}function b(){p.style.display="none"}let d,u=1,l="",f=0,m=0;a.style.display="none";g.addEventListener("submit",x);a.addEventListener("click",H);async function x(r){if(r.preventDefault(),l=r.target.elements.query.value.trim(),y.innerHTML="",!l){c.error({title:"Error",message:"Please enter a search query!"});return}a.style.display="none",u=1,f=0,m=0,y.innerHTML="",h(),await L(l,u),b(),g.reset()}async function L(r,s){try{const o=await v(r,s);if(o.hits.length===0){a.style.display="none",c.warning({title:"No results",message:"Sorry, there are no images matching your search query."});return}f=o.totalHits,m+=o.hits.length,M(o.hits),D(),s>1&&N(),O()}catch(o){c.error({color:"red",message:`Error fetching more images: ${o.message}`})}}async function H(){u++,a.disabled=!0,h(),await L(l,u),b()}function O(){m>=f?(a.style.display="none",c.error({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})):(a.style.display="block",a.disabled=!1)}function D(){d?d.refresh():d=new P(".gallery-item a",{captionsData:"alt",captionDelay:250})}function N(){const r=document.querySelector(".gallery-item");if(r){const{height:s}=r.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
